### ISSUE TITLE
ipython: cursor not moved after inserting spaces at the end of the line

### ISSUE THREAD

**Issue by blahgeek** [akermu/emacs-libvterm#398] opened 2020-09-13 02:32 UTC
How to reproduce:

- Open `ipython`
- Press space

Expected behavior: cursor moves to right

Actual behavior: cursor not moved

**Comment by Sbozzolo** [comment] 2020-09-17 02:02
I will close this issue as a duplicate of #196.

**Closed by Sbozzolo** 2020-09-17 02:02 UTC
