### ISSUE TITLE
Vterm causing emacs to segfault

### ISSUE THREAD

**Issue by xircon** [akermu/emacs-libvterm#565] opened 2021-12-15 20:34 UTC
```
Fatal error 11: Segmentation fault
Backtrace:
emacs(emacs_backtrace+0x52)[0x56088bf0c272]
emacs(terminate_due_to_signal+0x8c)[0x56088bdfb4f9]
emacs(+0x7aa33)[0x56088bdfba33]
emacs(+0x18954e)[0x56088bf0a54e]
emacs(+0x1895ca)[0x56088bf0a5ca]
/usr/lib/libpthread.so.0(+0x13870)[0x7f7bc75a0870]
/home/xircon/.emacs.d/straight/build/vterm/vterm-module.so(emacs_module_init+0x3a)[0x7f7bc0eb7c7a]
emacs(Fmodule_load+0x10c)[0x56088bf9edfc]
emacs(Fload+0x777)[0x56088bf9c8f7]
emacs(save_match_data_load+0x5b)[0x56088bf9cdfb]
emacs(Frequire+0x21b)[0x56088bf8178b]
emacs(Ffuncall+0x293)[0x56088bf71403]
emacs(exec_byte_code+0x321)[0x56088bfaf311]
emacs(eval_sub+0x4f7)[0x56088bf73b67]
emacs(+0x21b02e)[0x56088bf9c02e]
emacs(Fload+0x9c1)[0x56088bf9cb41]
emacs(save_match_data_load+0x5b)[0x56088bf9cdfb]
emacs(Frequire+0x21b)[0x56088bf8178b]
emacs(eval_sub+0x4f7)[0x56088bf73b67]
emacs(eval_sub+0x3b2)[0x56088bf73a22]
emacs(Fif+0x11)[0x56088bf743a1]
emacs(eval_sub+0x43a)[0x56088bf73aaa]
emacs(internal_lisp_condition_case+0x289)[0x56088bf75659]
emacs(eval_sub+0x43a)[0x56088bf73aaa]
emacs(+0x214399)[0x56088bf95399]
emacs(+0x21af9f)[0x56088bf9bf9f]
emacs(Feval_buffer+0x148)[0x56088bf9cf68]
emacs(Ffuncall+0x293)[0x56088bf71403]
emacs(exec_byte_code+0x321)[0x56088bfaf311]
emacs(Ffuncall+0x1df)[0x56088bf7134f]
emacs(call4+0x39)[0x56088bf715b9]
emacs(Fload+0xb22)[0x56088bf9cca2]
emacs(Ffuncall+0x293)[0x56088bf71403]
emacs(exec_byte_code+0x321)[0x56088bfaf311]
emacs(Ffuncall+0x1df)[0x56088bf7134f]
emacs(exec_byte_code+0x321)[0x56088bfaf311]
emacs(+0x1f3931)[0x56088bf74931]
emacs(eval_sub+0x2b6)[0x56088bf73926]
emacs(+0x21af9f)[0x56088bf9bf9f]
emacs(Feval_buffer+0x148)[0x56088bf9cf68]
emacs(Ffuncall+0x293)[0x56088bf71403]
...
[1]    75370 segmentation fault (core dumped)  emacs
```
Installed:
```
1 archlinuxcn/emacs-git 29.0.50.152643-1 [installed]
````
Last known good package:
```
emacs-native-comp-git-29.0.50.152393-1-x86_64.pkg.tar.zst
```
I should point out that this occurs for me on both recent -git and native-comp-git packages.  I moved to emacs-git after going to the aur page because of this problem and seeing the maintainers comments.

Removing references to vterm in my config fixes the problem.

**Comment by Sbozzolo** [comment] 2021-12-16 01:57
Duplicate of https://github.com/akermu/emacs-libvterm/issues/559. Please, see PR linked to the issue.

**Closed by Sbozzolo** 2021-12-16 01:57 UTC
