### ISSUE TITLE
Compilation of emacs-libvterm module failed

### ISSUE THREAD

**Issue by banz-ai** [akermu/emacs-libvterm#169] opened 2019-10-16 05:53 UTC
After updating vterm from MELPA I'm getting the following error.

cmake: error while loading shared libraries: libjsoncpp.so.20: cannot open shared object file: No such file or directory
make: *** No targets specified and no makefile found.  Stop.

Any help on how I can solve this?

**Comment by SriramRamesh** [comment] 2019-12-24 06:30
I had the same issue.
1. Go to .emacs.d/.local/straight/build/vterm/
2. mkdir -p build
3. install cmake  and libtool-bin
(if you use mac ( brew install cmake, brew install libtool))
4. `mkdir -p build
cd build
cmake ..
make` (it is there in the readme)

**Comment by Sbozzolo** [comment] 2020-02-13 01:04
Is the issue still relevant, or can it be closed?

**Comment by tamasgal** [comment] 2020-02-21 12:56
So the problem is that `cmake` is a requirement and it is not displayed in the error message.

After installing `cmake` on (e.g. on macOS via `brew install cmake`) the next error is more descriptive:

```
HEAD is now at 89675ff Recognise SGR 4:3 for curly underline
[ 25%] No patch step for 'libvterm'
[ 33%] Performing update step for 'libvterm'
[ 41%] No configure step for 'libvterm'
[ 50%] Performing build step for 'libvterm'
TBL src/encoding/DECdrawing.tbl
TBL src/encoding/uk.tbl
CC src/encoding.c
make[3]: glibtool: No such file or directory
make[3]: *** [src/encoding.lo] Error 1
make[2]: *** [libvterm-prefix/src/libvterm-stamp/libvterm-build] Error 2
make[1]: *** [CMakeFiles/libvterm.dir/all] Error 2
make: *** [all] Error 2
```

As @SriramRamesh pointed out, it's the missing `libtool` (on macOS via `brew install libtool`).

After that, opening a new vterm will trigger a compilation and it will work without any further tweaks.

I think you can close this, unless you can somehow improve the initial error message.

**Comment by Sbozzolo** [comment] 2020-02-21 15:02
I guess we can improve our compilation system by including a check for `cmake` and `libtool`. 
Is `glibtool` the name of the executable on macOS?

**Comment by tamasgal** [comment] 2020-02-21 15:41
Alright, sounds like a plan ;)

Yep, it is.

**Comment by Sbozzolo** [comment] 2020-03-08 16:51
PR #261 improves dependency checking and build system in general. Hopefully, now it will be easier to compile/inform the user of what's missing.

**Closed by Sbozzolo** 2020-03-08 16:51 UTC

**Comment by tamasgal** [comment] 2020-03-08 17:18
Thanks!

**Comment by mcveight** [comment] 2021-05-03 20:46
I was got the same problem and I fixed installing gcc hahaha

**Comment by zdrudi** [comment] 2021-05-21 20:40
So I had the same issue trying to compile on OS X Catalina. I had all dependencies installed (cmake & libtool), and needed to follow SriramRamesh's instructions. Well, his directory was wrong for me. For posterity:
```
cd ~
cd .emacs.d/elpa/vterm-20210409.1558
mkdir build
cd build
cmake ..
make
```

**Comment by bryanmobrien** [comment] 2021-05-26 16:16
failing on Big Sur as well.  My directory:
```
~/.emacs.d/elpa/27.2/develop/vterm-20210409.1558
```

**Comment by Noah-Huppert** [comment] 2021-08-19 17:02
If you get this error but CMake is installed ensure that the directory the CMake binary is located in is also in the Emacs `exec-path` variable.

**Comment by fmgornick** [comment] 2023-10-15 18:04
I had cmake installed with homebrew, but emacs still couldn't find the binary even after adding it to the exec path

I was able to fix it by changing the `PATH` env variable,
```
(setenv "PATH" (concat "/opt/homebrew/bin:" (getenv "PATH")))
```

**Comment by askdkc** [comment] 2024-02-06 08:11
@fmgornick 

Thanks for the info! It works really well!!
