### ISSUE TITLE
which-key and helm/ivy popups interfere with point

### ISSUE THREAD

**Issue by leungbk** [akermu/emacs-libvterm#407] opened 2020-09-22 22:53 UTC
With a bare config containing something like

```elisp
(require 'vterm)

(require 'which-key)
(which-key-mode 1)

(require 'ivy)
(ivy-mode 1)
```

I find that quickly pressing `C-c C-p` in `vterm` moves to the previous prompt as expected, but after pressing `C-c` and waiting for the `which-key` popup to appear, `point` ends up moving to the active prompt.

Something similar happens with `ivy` and `helm`. For example when `point` is further up in the `vterm` buffer and I press `C-x b` without triggering the `which-key` popup. Whether I exit the `ivy`/`helm` minibuffer with `C-g`, or finish the `completing-read` session normally and return to the `vterm` buffer, I find that `point` is at the active prompt of the `vterm` buffer.

**Comment by Sbozzolo** [comment] 2020-10-06 05:35
Thanks, this is due to redrawing the window when the size changes (function `vterm--window-adjust-process-window-size`).
It is a bug.

**Comment by Sbozzolo** [comment] 2020-11-02 02:02
I close this as duplicate of #149. The root problem is the redrawing the window.

**Closed by Sbozzolo** 2020-11-02 02:02 UTC
