### ISSUE TITLE
Why does `M-w` copy the full line?

### ISSUE THREAD

**Issue by SreenivasVRao** [akermu/emacs-libvterm#367] opened 2020-07-13 15:01 UTC
Hi,

I'm noticing that in vterm-copy-mode, M-w copies the full line instead of the highlighted region. Is there a fix?

OSX emacs 26.3 spacemacs develop, running the macports version of emacs.

**Comment by Sbozzolo** [comment] 2020-07-13 15:06
`M-w` should copy the active region, as it should be bound to `kill-ring-save`, a built-in Emacs function.

I suspect that if that doesn't work, it is because of your configuration. Can you try to reproduce the bug with `emacs -Q`?

**Comment by Sbozzolo** [comment] 2020-07-13 15:20
Or it may be spacemacs. What is `M-w` bound to?

**Comment by SreenivasVRao** [comment] 2020-07-13 15:20
yup, seeing this occur with emacs -Q.

```
(add-to-list 'load-path "~/.emacs.d/elpa/vterm-20200418.1610")
(require 'vterm)
```

evaluated in scratch buffer.

1. launch vterm `M-x vterm`
2. `mkdir test && cd test && touch foo.txt`
3. `ls -lrt foo.txt`
4. `C-c C-t` to enable copy mode
5.  Highlight the `foo.txt` in the output. `M-w` to copy.
6. `RET` to return to vterm mode
7. `C-y` to yank - you'll see the full line pasted instead of just `foo.txt`

**Comment by Sbozzolo** [comment] 2020-07-13 15:24
Okay, I understand the problem. When you press `RET`, you are invoking the command `vterm-copy-mode-done`. This command copies the region, it the region is active, or the line, if the region is not active, and then quits the copy mode. You can try this:
select the region you want to copy, and just press `RET`. This will copy the region and bring you back to the usual vterm. Alternatively, exit vterm-copy-mode with `C-c C-t` instead of `RET`.

**Comment by SreenivasVRao** [comment] 2020-07-13 15:26
Is it possible to remap `M-w` to do this? Muscle memory is strong! :D

**Comment by Sbozzolo** [comment] 2020-07-13 15:28
This should work `(define-key vterm-copy-mode-map (kbd "M-w")  #'vterm-copy-mode-done)`

**Comment by Sbozzolo** [comment] 2020-07-13 22:10
Can I close this issue?

**Comment by SreenivasVRao** [comment] 2020-07-13 22:16
Yup - I just tried your solution and it worked! :)

**Closed** 2020-07-13 22:17 UTC
