### ISSUE TITLE
Cursor position not set correctly in vim

### ISSUE THREAD

**Issue by fydai** [akermu/emacs-libvterm#196] opened 2019-12-04 04:50 UTC
I launched vim in libvterm, entered insert mode, and insert a few spaces.

I would expect the cursor to be shifted to the right a few characters, but instead it is still on the first column. If I insert a non-space character, the cursor jumps to the right, to the expected position.

This doesn't occur with nano, or when there is a right margin to vim (e.g. with `:set colorcolumn=80`). This leads me to believe that the issue is with setting the point position in emacs, from the cursor position in libvterm.

I think a potential fix would be to detect when argument to `forward_char`  (https://github.com/akermu/emacs-libvterm/blob/1006fb8d1d61c79fe05827929fce0a0f6270798c/vterm-module.c#L428) would exceed the length of the line, and insert spaces to the line as padding.

I would be interested in submitting a patch if it would help.

**Comment by jixiuf** [comment] 2019-12-04 07:30
pull request are welcome

**Comment by leoalekseyev** [comment] 2020-06-06 22:04
@fydai I am experiencing the same bug, any progress on the fix? I could help with the fix but would need some more context about the correct way to set point position on elisp side.

**Comment by schellj** [comment] 2020-09-05 01:07
I'm also experiencing this issue. Basically, for any non-shell program run from within vterm that has a prompt (mysql client, etc), the cursor is placed after the last non-space character on a line. This is the only thing bothering me about vterm right now, so any fix or workaround would be very appreciated.

**Comment by schellj** [comment] 2020-09-14 00:15
I've had a bit of time to try to debug this issue.

The root cause seems to be that some applications, like Vim or the MySQL cli, seem to emit null characters instead spaces. With the previous logic of considering a cell EOL if all cells to its right are null makes it so that typing spaces in those applications have no effect on the location of the cursor, making entering input more difficult.

This commit attempts to deal with that by considering any extant cell to not be EOL: https://github.com/schellj/emacs-libvterm/commit/24dfdc2a263bbbeca2a3ceacad894f9568aa3fba. One observed downside with this change is that executing vterm-end-of-line in vterm-copy-mode moves the cursor all the way to the right edge of the line instead of to the last non-null character. I'll keep trying to think of a better solution, but improved input behavior is worth that downside to me for now.

**Comment by Sbozzolo** [comment] 2020-09-14 00:25
Thanks. I haven't looked at #399 yet, but that should solve the issue. Why don't you test it?

**Comment by schellj** [comment] 2020-09-14 15:52
Thanks, I'll test that PR today.

**Comment by jixiuf** [comment] 2021-02-07 10:04
Should be fixed, after #399 is merged.

**Closed by jixiuf** 2021-02-07 10:04 UTC
