### ISSUE TITLE
Terminal hangs. 

### ISSUE THREAD

**Issue by mbrumlow** [akermu/emacs-libvterm#114] opened 2019-08-07 00:30 UTC
First off, this is amazing and thanks. 

You can reliable get a terminal to hang by opening two terminals, and in one run something like "find /" or top with update speed of 0. The second terminal will stop responding until you kill the command in the other or let it finish.

**Comment by mbrumlow** [comment] 2019-08-12 22:48
Correction, top does not show this behavior. Running find / does though.

**Comment by akermu** [comment] 2019-08-13 07:30
This also happens if the update speed is not nil for me. I think it has to do with how emacs handles process I/O. But I'll have to investigate further.

**Comment by akermu** [comment] 2019-08-16 14:31
Okay it's happening because of our hook for `window-size-change-functions`.

**Comment by Sbozzolo** [comment] 2020-02-13 01:11
#129 seems to solve this, and I cannot reproduce the bug on master. I am closing this issue. Feel free to re-open if the problem appears again.

**Closed by Sbozzolo** 2020-02-13 01:11 UTC
